pdev:'set'

diff --git a/Dockerfile.r2g b/Dockerfile.r2g
--- a/Dockerfile.r2g
+++ b/Dockerfile.r2g
@@ -8,7 +8,7 @@ RUN apt-get install -y netcat
 RUN sudo echo "node ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
 
 USER node
-RUN mkdir -p /home/node/app
+RUN mkdir -p /home/node/app/node_modules/r2g
 WORKDIR /home/node/app
 
 RUN sudo chmod -R 777  /home/node
@@ -32,7 +32,7 @@ COPY . .
 RUN sudo chmod -R 777  /home/node
 
 ENV PATH="./node_modules/.bin:${PATH}"
-RUN tsc || echo "could not compile"
+RUN tsc > /dev/null || echo "could not compile"
 
 #ENTRYPOINT ["docker_r2g"]
 
